[tool.pyright]
reportMissingImports = false
reportUnboundVariable = false

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [ # defaults: ["E4", "E7", "E9", "F"], see https://docs.astral.sh/ruff/rules/
  "A",    # flake8-builtins
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "E",    # pycodestyle Error
  "F",    # Pyflakes
  "FLY",  # flynt
  "FURB", # refurb
  "I",    # isort
  "NPY",  # NumPy-specific rules
  "PD",   # pandas-vet
  "PL",   # Pylint
  "RUF",  # Ruff-specific rules
  "SIM",  # flake8-simplify
  "UP",   # pyupgrade
  "W",    # pycodestyle Warning
]
ignore = [
  "PD901", # pandas-df-variable-name
  "PLR09", # too-many-...
]
